"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var GoodsForm = function () { return (React.createElement("div", { className: "goods__form" },
    React.createElement("div", { className: "goods__form-head" }, "Product Categories"),
    React.createElement("div", { className: "goods__categories" },
        React.createElement("ul", { className: "goods__categories-list" },
            React.createElement("li", { className: "goods__categories-item" },
                React.createElement("div", { className: "checkbox" },
                    React.createElement("label", { className: "checkbox__label" },
                        React.createElement("input", { className: "checkbox__elem", type: "checkbox", name: "create" }),
                        React.createElement("span", null, "T-Shirt test")))),
            React.createElement("li", { className: "goods__categories-item" },
                React.createElement("div", { className: "checkbox" },
                    React.createElement("label", { className: "checkbox__label" },
                        React.createElement("input", { className: "checkbox__elem", type: "checkbox", name: "create" }),
                        React.createElement("span", null, "T-Shirt test")))),
            React.createElement("li", { className: "goods__categories-item" },
                React.createElement("div", { className: "checkbox" },
                    React.createElement("label", { className: "checkbox__label" },
                        React.createElement("input", { className: "checkbox__elem", type: "checkbox", name: "create" }),
                        React.createElement("span", null, "T-Shirt test")))))),
    React.createElement("div", { className: "goods__form-head" }, "Filter by color"),
    React.createElement("div", { className: "goods__color" },
        React.createElement("div", { className: "goods__color-item goods__color-item_red" }),
        React.createElement("div", { className: "goods__color-item goods__color-item_green" }),
        React.createElement("div", { className: "goods__color-item goods__color-item_blue" }),
        React.createElement("div", { className: "goods__color-item goods__color-item_purple goods__color-item_active" }),
        React.createElement("div", { className: "goods__color-item goods__color-item_yellow" }),
        React.createElement("div", { className: "goods__color-item goods__color-item_black" })),
    React.createElement("div", { className: "goods__form-head" }, "Filter by size"),
    React.createElement("ul", { className: "goods__size" },
        React.createElement("li", { className: "goods__size-item" }, "XS"),
        React.createElement("li", { className: "goods__size-item goods__size-item_active" }, "S"),
        React.createElement("li", { className: "goods__size-item" }, "M"),
        React.createElement("li", { className: "goods__size-item" }, "L"),
        React.createElement("li", { className: "goods__size-item" }, "XL")),
    React.createElement("div", { className: "goods__form-head" }, "Filter by price"),
    React.createElement("div", { className: "goods__price" },
        React.createElement("div", { className: "goods__price-point left" }),
        React.createElement("div", { className: "goods__price-indicator" }),
        React.createElement("div", { className: "goods__price-point right" })),
    React.createElement("div", { className: "goods__price-range" }, "Price: $5 - $100"),
    React.createElement("button", { type: "button", className: "goods__form-button" }, "Filter"))); };
exports.default = GoodsForm;

//# sourceMappingURL=GoodsForm.js.map
