"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var ProductInfo = function () { return (React.createElement("div", { className: "product" },
    React.createElement("div", { className: "container" },
        React.createElement("div", { className: "row space-between product__content" },
            React.createElement("div", { className: "product__images" },
                React.createElement("div", { className: "product__image product__image_lg" },
                    React.createElement("img", { src: "/image/product.png", width: "100%" })),
                React.createElement("div", { className: "row space-between" },
                    React.createElement("div", { className: "product__image product__image_sm" },
                        React.createElement("img", { src: "/image/product.png", width: "100%" })),
                    React.createElement("div", { className: "product__image product__image_sm" },
                        React.createElement("img", { src: "/image/product.png", width: "100%" })),
                    React.createElement("div", { className: "product__image product__image_sm" },
                        React.createElement("img", { src: "/image/product.png", width: "100%" })))),
            React.createElement("div", { className: "product__info" },
                React.createElement("div", { className: "row space-between product__info-head" },
                    React.createElement("div", { className: "product__name" }, "Biker hoodie"),
                    React.createElement("div", { className: "product__price" }, "$24.00")),
                React.createElement("div", { className: "product__description" }, "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto aspernatur at consectetur cum cupiditate dolores doloribus exercitationem explicabo fuga fugiat ipsum iusto, labore natus nisi tempore, tenetur ullam ut veniam!"),
                React.createElement("div", { className: "row space-between product__facilities" },
                    React.createElement("div", { className: "product__size row" },
                        React.createElement("p", null, "Size:"),
                        React.createElement("ul", { className: "product__size-list" },
                            React.createElement("li", { className: "product__size-item" }, "XS"),
                            React.createElement("li", { className: "product__size-item" }, "S"),
                            React.createElement("li", { className: "product__size-item product__size-item_active" }, "M"),
                            React.createElement("li", { className: "product__size-item" }, "L"))),
                    React.createElement("div", { className: "product__color row" },
                        React.createElement("p", null, "Color:"),
                        React.createElement("div", { className: "goods__color goods__color_sm" },
                            React.createElement("div", { className: "goods__color-item goods__color-item_red" }),
                            React.createElement("div", { className: "goods__color-item goods__color-item_green" }),
                            React.createElement("div", { className: "goods__color-item goods__color-item_blue" }),
                            React.createElement("div", { className: "goods__color-item goods__color-item_purple\r\n\t\t\t\t\t\t\t\t\tgoods__color-item_active" }),
                            React.createElement("div", { className: "goods__color-item goods__color-item_yellow" }),
                            React.createElement("div", { className: "goods__color-item goods__color-item_black" })))),
                React.createElement("div", { className: "my-pad" },
                    React.createElement("div", { className: "order" },
                        React.createElement("div", { className: "order__quantity" },
                            React.createElement("b", { className: "order__quantity-head" }, "Quantity:"),
                            React.createElement("span", { className: "order__quantity-count", contentEditable: true }, "1")),
                        React.createElement("div", { className: "order__actions row mt-2" },
                            React.createElement("div", { className: "order__like" },
                                React.createElement("i", { className: "fas fa-heart" })),
                            React.createElement("div", { className: "order__add" }, "Add to cart")))),
                React.createElement("div", { className: "product__share" },
                    React.createElement("b", null, "Share in:"),
                    React.createElement("i", { className: "fab fa-facebook-f product__share-soc" }),
                    React.createElement("i", { className: "fab fa-twitter product__share-soc" }),
                    React.createElement("i", { className: "fab fa-pinterest-p product__share-soc" })),
                React.createElement("div", { className: "product__categories" },
                    React.createElement("b", null, "Categories:"),
                    React.createElement("span", { className: "ml-1" },
                        React.createElement("a", { className: "product__categories-item", href: "#" }, "Fashion, \u00A0"),
                        React.createElement("a", { className: "product__categories-item", href: "#" }, "Men clothes"))),
                React.createElement("div", { className: "product__categories" },
                    React.createElement("b", null, "Tags:"),
                    React.createElement("span", { className: "ml-1" },
                        React.createElement("a", { className: "product__categories-item", href: "#" }, "Fashion, \u00A0"),
                        React.createElement("a", { className: "product__categories-item", href: "#" }, "Men clothes"))),
                React.createElement("div", { className: "product__mark my-pad" },
                    React.createElement("b", { className: "product__mark-head" }, "Average mark:"),
                    React.createElement("span", null, "5.0"))))))); };
exports.default = ProductInfo;

//# sourceMappingURL=ProductInfo.js.map
