"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CATEGORY_LOAD_START = 'CATEGORY_LOAD_START';
exports.CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS';
exports.CATEGORY_LOAD_ERROR = 'CATEGORY_LOAD_ERROR';
exports.CART_ADD = 'CART_ADD';
exports.CART_REMOVE = 'CART_REMOVE';
exports.CART_RESET = 'CART_RESET';
exports.CART_UPDATE = 'CART_UPDATE';
exports.USER_LOAD_START = 'USER_LOAD_START';
exports.USER_LOAD_ERROR = 'USER_LOAD_ERROR';
exports.USER_LOAD_SUCCESSFULL = 'USER_LOAD_SUCCESSFULL';
exports.USER_LOGIN = 'USER_LOGIN';
exports.USER_LOGOUT = 'USER_LOGOUT';
exports.REGISTER_START = 'REGISTER_START';
exports.REGISTER_ERROR = 'REGISTER_ERROR';
exports.REGISTER_SUCCESSFULL = 'REGISTER_SUCCESSFULL';

//# sourceMappingURL=actionTypes.js.map
